#!/usr/bin/env bash
# Regenerates docs/<dir>/INDEX.md by listing every file in the folder with
# its first Markdown heading (or first non-blank line) as the title.
# Usage: scripts/generate-doc-index.sh docs/research "Research"
set -euo pipefail

dir="$1"
title="${2:-$(basename "$dir")}"
index="$dir/INDEX.md"

{
  echo "# $title Index"
  echo
  echo "Generated by \`scripts/generate-doc-index.sh\`; do not hand-edit entries below, regenerate instead."
  echo
  for f in "$dir"/*; do
    base="$(basename "$f")"
    [ "$base" = "INDEX.md" ] && continue
    [ -f "$f" ] || continue
    heading="$(grep -m1 -E '^#+ ' "$f" 2>/dev/null | sed -E 's/^#+ *//' || true)"
    [ -z "$heading" ] && heading="$(head -n1 "$f" 2>/dev/null || true)"
    [ -z "$heading" ] && heading="$base"
    echo "- [$base]($base): $heading"
  done
} > "$index"
